// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvWg0FjyKBUwnMcHkULGsfGQSQ8eJ09ts',
    appId: '1:351866687950:android:160052f5d7329d97491b9f',
    messagingSenderId: '351866687950',
    projectId: 'gym-fab37',
    storageBucket: 'gym-fab37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH9xHne6kiTrudbL4E0isc68ZEm3YVGYY',
    appId: '1:351866687950:ios:9bf83f8d64261b0f491b9f',
    messagingSenderId: '351866687950',
    projectId: 'gym-fab37',
    storageBucket: 'gym-fab37.firebasestorage.app',
    androidClientId: '351866687950-bqq9hjtobhp19rgtfdq7oijghrlg5ih4.apps.googleusercontent.com',
    iosClientId: '351866687950-jntmk64bqfa10beab0d2m4jgn3c8dkkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3',
  );

}